sudo: required
services:
  - docker

before_install:
  - docker build -t ravipati2008/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ravipati2008/react-test npm test

after_success:
  - docker build -t ravipati2008/fibonacci-client ./client
  - docker build -t ravipati2008/fibonacci-nginx ./nginx
  - docker build -t ravipati2008/fibonacci-server ./server
  - docker build -t ravipati2008/fibonacci-worker ./worker
  # Login to docker cli and push these images to docker hub
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ravipati2008/fibonacci-client
  - docker push ravipati2008/fibonacci-nginx
  - docker push ravipati2008/fibonacci-server
  - docker push ravipati2008/fibonacci-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-fibonacci'
  env: 'Docker-fibonacci-env'
  bucket_name: 'elasticbeanstalk-us-east-2-744334807452'
  bucket_path: 'docker-fibonacci'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY