version: '3'
services:
  api:
    image: "ravipati2008/fibonacci-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PG_USER=$PG_USER
      - PG_HOST=$PG_HOST
      - PG_DATABASE=$PG_DATABASE
      - PG_PWD=$PG_PWD
      - PG_PORT=$PG_PORT
  nginx:
    image: "ravipati2008/fibonacci-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
  client:
    image: "ravipati2008/fibonacci-client"
    mem_limit: 128m
    hostname: client
  worker:
    image: "ravipati2008/fibonacci-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT