version: '3'
services:
  api:
    image: "ravipati2008/fibonacci-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_DATABASE=postgres
      - PG_PWD=postgres_password
      - PG_PORT=5432
  nginx:
    image: "ravipati2008/fibonacci-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
  client:
    image: "ravipati2008/fibonacci-client"
    mem_limit: 128m
    hostname: client
  worker:
    image: "ravipati2008/fibonacci-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT